folio-org/mod-oa

service/build.gradle
The same for http://maven.k-int.com/content/repositories/public
A machine-in-the-middle attack can change the download
to contain malware. Using https will prevent this.
Details: https://issues.folio.org/browse/FOLIO-3044
=> FOLIO-3045: Replace http by https in http://maven.indexdata.com/

service/grails-app/i18n/messages.properties
Added separate unique messages fro Patry email/orcid so that client POST/PUTs will be able to discern the differing errors
MODOA-19
=> chore: Added uniqueness messages for backend

service/grails-app/domain/Address.groovy, service/grails-app/domain/Party.groovy, service/grails-app/domain/PartyAddress.groovy, service/grails-app/migrations/create-mod-oa.groovy, service/grails-app/views/address/_address.gson, service/grails-app/views/party/_party.gson, service/grails-app/views/partyAddress/_partyAddress.gson
Added new domain classes "Address" and "PartyAddress". This modelling is to keep the idea of an address and the idea of a Party logically separate. It also will allow for many-many relationships down the line, and also for addresses to sit both on a party, but also an institution etc. While this may not be necessary for OA per se, it will be necessary in other projects. Since we hope to migrate this work over to using something more general in future, this structure should hopefully allow for a more seamless transition.
MODOA-18
=> feat: Addresses

service/grails-app/migrations/create-mod-oa.groovy
Added foreign key constraints to the following ref data columns:
- PublicationIdentifier.Type
- PublicationRequest.License
- PublicationRequest.Publisher
- PublicationRequest.Subtype
- PublicationStatus.PublicationStatus
In order to prevent deletion of ref data values when they're in use
UIOA-125
=> feat: Foreign Key Constraints

service/src/main/okapi/ModuleDescriptor-template.json
Added permission names, display names and descriptions for all missing correspondence permissions
=> feat: Correspondence item permissions

service/grails-app/domain/org/olf/oa/Party.groovy, service/grails-app/domain/org/olf/oa/PublicationRequest.groovy, service/grails-app/migrations/create-mod-oa.groovy, service/grails-app/views/party/_party.gson, service/grails-app/views/publicationRequest/_publicationRequest.gson
Changed publication request and party models, faculty/department is now insitutionLevel1/2, correspondingFaculty/Department is now correspondingInstitutionLevel1/2
Added SQL to migrate all data from faculty/department and corresponding faculty/department to institutionLevel1/2 and correspondingInstitutionLevel1/2 respectively and dropped deprecated columns and foreign keys
[MODOA-31](https://issues.folio.org/browse/MODOA-31)
=> feat: Faculty/department migration

service/grails-app/controllers/org/olf/oa/ReportsController.groovy
Added support so that multiple charge categories/statuses can be added to the query parameters, additionally added conditionals so that if no payment period, charge categories or statuses are supplied, query will match with all charges on the respective field
[MODOA-28](https://issues.folio.org/browse/MODOA-28)
=> feat:Multiple/Null query parameters

service/grails-app/migrations/create-mod-oa.groovy, service/grails-app/services/org/olf/oa/BibReferenceService.groovy
Added unique key constraint to ensure that namespace, value combinations are unique, additionally added checks within identifierLookup to ensure that an error is thrown when more than one matching identifier namespace, value combination is returned
[MODOA-35](https://issues.folio.org/browse/MODOA-35)
=> fix: Duplicate Identifiers

service/grails-app/controllers/org/olf/oa/ReportsController.groovy
Fixed error which was being thrown regarding report query string, fixed by surrounding lists within parenthesis
Fixed the OpenAPC charges report to correctly use the ISSN value from the associated work as opposed to the publication identifier
[MODOA-36](https://issues.folio.org/browse/MODOA-36)
[MODOA-37](https://issues.folio.org/browse/MODOA-37)
=> fix: Report query and ISSN

service/grails-app/domain/org/olf/oa/Correspondence.groovy
Changed default internal on correspondence status from true to false to allow for editing within settings
[MODOA-41](https://issues.folio.org/browse/MODOA-41)
=> fix: Editable correspondence status

NEWS.md, service/grails-app/migrations/module-tenant-changelog.groovy, service/grails-app/migrations/update-mod-oa-1-1.groovy
Changed p_main_email datatype from VARCHAR(36) to VARCHAR(255)
[MODOA-44](https://issues.folio.org/browse/MODOA-44)
=> fix: Main email data type

service/grails-app/domain/org/olf/oa/workflow/ChecklistItemDefinition.groovy
Fixed function for handling creation of checklist item name from provided label, now all accented letters are replaced with a lowercase version without the accent and all special characters are replaced with an underscore
[UIOA-211](https://issues.folio.org/browse/UIOA-211)
=> fix: Checklist item name regex

NEWS.md, service/grails-app/migrations/update-mod-oa-1-1.groovy
Modified pr_title datatype from VARCHAR(255) to VARCHAR(4096) to accommodate longer publication titles
[MODOA-46](https://issues.folio.org/browse/MODOA-46)
=> fix: Publication title datatype

service/build.gradle
Bumped hibernate-core dependency to version 5.4.33
[MODOA-47](https://issues.folio.org/browse/MODOA-47)
=> build: Hibernate-core dependency bump

service/build.gradle
Bumped commons-io from 2.6 to 2.7
[MODOA-54](https://issues.folio.org/browse/MODOA-54)
=> build: Bumped commons-io version

NEWS.md, service/build.gradle
Bumped spring-webmvc version from 5.3.19 to 5.3.28
[MODOA-55](https://issues.folio.org/browse/MODOA-55)
=> build: Bumped spring-webmvc version

service/grails-app/domain/org/olf/oa/Charge.groovy
Added optional chaining to getEstimatedInvoicePrice discount calculation to prevent errors when discount type is not present
[MODOA-57](https://issues.folio.org/browse/MODOA-57)
=> fix: DiscountType optional chaining

service/src/main/okapi/ModuleDescriptor-template.json
Tweaked some endpoints so that they are using fine grained permissions as opposed to permission sets, additionally changed so that the same permissions are not used across multiple endpoints
=> ERM-3211: Endpoints should be protected by fine-grained permissions

.github/workflows/gradle.yml, .github/workflows/validate-module.yml, service/src/main/okapi/ModuleDescriptor-template.json
- Added github actions file to enable validation of the module descriptor (ahead of trying to crank out the permission fixes
- Permission tweaks to satisfy Eureka
=> Permissions fixes

service/src/main/okapi/ModuleDescriptor-template.json
build: Add optional okapi dependencies to ModuleDescriptor
MODOA-69
=> MODOA-69: Missing interface dependencies in module descriptor in mod-oa

NEWS.md, service/gradle.properties
Added NEWS section and changed version to 3.1.0
MODOA-64
DO NOT MERGE - until mod-oa release 3.1.0
=> chore: Release 3.1.0
