folio-org/mod-oa

scripts/register_and_enable_dev.sh
scripts/test_direct.sh
service/src/main/okapi/DeploymentDescriptor-template.json
service/src/main/okapi/DeploymentDescriptorDev-template.json
service/src/main/okapi/ModuleDescriptor-template.json

Moved module over to port 8080, matching setup of mod-service-integration

fix: Fixed ports

---

service/src/main/okapi/ModuleDescriptor-template.json

New refdata endpoints and permissions for those. POST, PUT, and DELETE

feat: New endpoints

---

service/grails-app/conf/application.yml

Changed date Format for month from mm to MM

fix: mm -> MM

---

service/grails-app/domain/Funder.groovy
service/grails-app/domain/PublicationRequest.groovy
service/grails-app/domain/PublicationRequestHistory.groovy
service/grails-app/migrations/create-mod-oa.groovy

changed dateModified fields over to lastUpdated to allow grails to automatically fill in the details

refactor: dateModifier -> lastUpdated

---

service/grails-app/domain/PublicationStatus.groovy
service/grails-app/migrations/create-mod-oa.groovy

Changed publicationStatus statusDate to LocalDate and column type to timestamp in  migrations

fix: Date changes

---

service/grails-app/domain/PublicationRequest.groovy

publicationStatuses now have a delete cascade so that we can remove them

fix: publicationStatus

---

service/grails-app/controllers/mod_oa/UrlMappings.groovy
service/grails-app/controllers/mod_oa/WorkController.groovy
service/grails-app/views/work/_work.gson
service/src/main/okapi/ModuleDescriptor-template.json

Added endpoint for Work, and expanded the instances for each Work
MODOA-8

feat: Work Controller

---

service/grails-app/domain/Funding.groovy
service/grails-app/domain/PublicationIdentifier.groovy
service/grails-app/domain/PublicationRequest.groovy
service/grails-app/domain/PublicationStatus.groovy

Set internal flag of several refdata fields to "false"
MODOA-11

fix: Internal

---

service/grails-app/domain/PublicationRequest.groovy
service/grails-app/migrations/create-mod-oa.groovy

Added a default to false and a migration to existing data for withoutAgreement boolean

fix: Default and migration

---

service/grails-app/domain/PublicationRequest.groovy
service/grails-app/migrations/create-mod-oa.groovy

Added foreign key constraints to a bunch of refdata columns to stop deletion of refdata values that are in use
UIOA-71

fix: Foreign Key Constraints

---

service/grails-app/domain/Charge.groovy
service/grails-app/migrations/create-mod-oa.groovy

in support of UIOA-75 - links to finance

feat: Add invoice reference and invoice line reference to charge - UIOA-75

---

service/grails-app/domain/Charge.groovy
service/grails-app/views/charge/_charge.gson

Estimated Invoice price and estimated price are now transients on the returned Charge
MODOA-20

feat: Estimated price transients

---

service/grails-app/services/mod_oa/BibReferenceService.groovy

Works are created through a citation system, which previously didn't take the new fields into account. This fixes that.
MODOA-21

fix: Added support to citation create

---

service/grails-app/domain/PublicationRequest.groovy
service/grails-app/migrations/create-mod-oa.groovy

Changed bookDateOfPublication field to VARCHAR(36), with grails validation ensuring athe string is of type "YYYY", "YYYY-MM" or "YYYY-MM-DD"
MODOA-23

chore: Change storage of monograph publication date to string

---

service/grails-app/domain/Address.groovy

Changed the nullable constraint for postalCode and country within Address from false to true

fix: Nullable address fields

---

service/src/main/okapi/ModuleDescriptor-template.json

Added endpoint for editing works along with associated permissions
MODOA-24

feat: Works edit

---

service/grails-app/controllers/mod_oa/ChargeController.groovy
service/grails-app/controllers/mod_oa/UrlMappings.groovy
service/src/main/okapi/ModuleDescriptor-template.json

Added charges controller, along with endpoints and permissions

feat: Charges controller

---

service/grails-app/migrations/create-mod-oa.groovy

Reverted changed to previous migration and dropped columns correctly

fix: Migration fix

---

service/grails-app/services/mod_oa/HousekeepingService.groovy

Added default tax as an AppSetting
UIOA-127

feat: Default tax setting

---

service/grails-app/domain/Charge.groovy
service/grails-app/migrations/create-mod-oa.groovy

Added charge date created/updated

feat: Charge metadata

---

service/grails-app/domain/org/olf/oa/workflow/ChecklistItemDefinition.groovy

Name for ChecklistItem can now be derived from the label when setting them up
MODOA-26

feat: NormName

---

service/grails-app/domain/org/olf/oa/workflow/ChecklistItem.groovy

Changed checklist refdata from Met, Not met, Other to Yes, No, Other

refactor: Checklist outcome refdata

---

service/grails-app/domain/org/olf/oa/Party.groovy
service/grails-app/domain/org/olf/oa/PublicationRequest.groovy
service/grails-app/migrations/create-mod-oa.groovy
service/grails-app/views/party/_party.gson
service/grails-app/views/publicationRequest/_publicationRequest.gson

Added faculty and department fields to publication request and party

feat: Faculty/Department fields

---

service/grails-app/domain/org/olf/oa/PublicationRequest.groovy
service/src/integration-test/groovy/org/olf/oa/PublicationRequestSpec.groovy

Changed refdata values for publication request status to Open and Closed
UIOA-149

feat: Request status values

---

service/grails-app/domain/org/olf/oa/Charge.groovy

Added 'Paid' to the charge status refdata

feat: Charge status refdata

---

service/grails-app/domain/org/olf/oa/Charge.groovy
service/grails-app/migrations/create-mod-oa.groovy

Added payment period to charge model
MODOA-27

feat: Payment period

---

service/grails-app/domain/org/olf/oa/Charge.groovy

Fixed  payment period regex to only validate for a 4 digit year as opposedto YYYY-MM-DD

fix: Payment period regex

---

service/grails-app/services/org/olf/oa/HousekeepingService.groovy

Added InstitutionName refdata value for usage in OpenAPC reporting
[MODOA-30](https://issues.folio.org/browse/MODOA-30), [UIOA-158](https://issues.folio.org/browse/UIOA-158)

feat: InstitutionName Refdatavalue

---

service/grails-app/controllers/org/olf/oa/ReportsController.groovy
service/grails-app/controllers/org/olf/oa/UrlMappings.groovy
service/src/integration-test/groovy/org/olf/oa/PublicationRequestSpec.groovy
service/src/main/okapi/ModuleDescriptor-template.json

Interim commit so there is something for the front end to talk to - refactor due shortly using something like https://github.com/folio-org/mod-agreements/blob/master/service/grails-app/controllers/org/olf/general/jobs/PersistentJobController.groovy#L151-L159

Modoa 28 in app reporting

---

service/grails-app/controllers/org/olf/oa/ReportsController.groovy

Added support for null categories/statuses and null payment period with the openapc bpc report format

feat: BPC report multiple/null params

---

service/grails-app/domain/org/olf/oa/PublicationRequest.groovy
service/grails-app/migrations/create-mod-oa.groovy

Added retrospective OA property to publication request domain model
[UIOA-187](https://issues.folio.org/browse/UIOA-187)

feat: Retrospective OA

---

service/grails-app/controllers/org/olf/oa/ReportsController.groovy

Added the new retroactiveOA property from the publication request domain model to be included in generated BPC reports

feat: BPC retrospective OA

---

service/grails-app/domain/org/olf/oa/PublicationIdentifier.groovy

Added 'ISBN' to PublicationIdentifiers 'type' refdatavalue as it will most likely be used extensively in generating BPC reports

feat: ISBN publication identifier

---

service/grails-app/domain/org/olf/oa/workflow/ChecklistItem.groovy

Changed checklist item status refdata from 'Required/Not Required' to 'Visibile/Hidden'

refactor: Checklist status refdata

---

service/grails-app/domain/org/olf/oa/PublicationRequest.groovy
service/grails-app/migrations/create-mod-oa.groovy
service/grails-app/views/publicationRequest/_publicationRequest.gson

Changed rejectionReason within publication request domain model to closureReason

refactor: Rejection reason

---

service/grails-app/domain/org/olf/oa/kb/TitleInstance.groovy
service/grails-app/domain/org/olf/oa/workflow/ChecklistItem.groovy

Changes default internal value to true for both ChecklistItem.Outcome and TitleInstance.PublicationType
[MODOA-40](https://issues.folio.org/browse/MODOA-40)

feat: Default internal changes

---

service/grails-app/controllers/org/olf/oa/ReportsController.groovy

Fixed report column header "instituion" to "institution"
[MODOA-42](https://issues.folio.org/browse/MODOA-42)

fix: Report institution header

---

service/grails-app/controllers/org/olf/oa/ReportsController.groovy

Fixed spelling of transformative agreement report header "institution"
[MODOA-42](https://issues.folio.org/browse/MODOA-42)

fix: Institution spelling

---

NEWS.md
service/gradle.properties

NEWS.md update and removed SNAPSHOT from version
[MODOA-43](https://issues.folio.org/browse/MODOA-43)

chore: Release 1.0.0

---

NEWS.md
service/build.gradle

Bumped dependencies for postgresql, opencsv, kafka-clients, commons-io
[MODOA-47](https://issues.folio.org/browse/MODOA-47)

build: Dependencies

---

service/grails-app/migrations/update-mod-oa-1-1.groovy

Added primary keys to several OA tables

feat: Primary keys

---

.github/workflows/gradle.yml

Added buildImage argument to build with gradle step and removed Publish docker image task from actions

build: Removed publish docker image

---

service/grails-app/init/org/olf/oa/Application.groovy

Implemented undertow servlet and enable scheduling annotation to application.groovy

feat: Undertow servlet

---

NEWS.md

Updated docs for primary keys and grails 5 changes

docs: Updated NEWS

---

service/build.gradle

Bumped kint web toolkit to 8.1.0-rc.4 from rc.3

build: Web toolkit bump

---

service/build.gradle

Bumped apache.kafka-clients to 3.5.1 from 2.3.0
[MODOA-53](https://issues.folio.org/browse/MODOA-53)

build: Kafka clients bump

---

NEWS.md
service/build.gradle
service/gradle.properties

- Added details to NEWS.md and removed SNAPSHOT from version #
- Bumped web-toolkit-ce to 8.1.4 from 8.1.0-rc.4

chore: Release 2.0.0

---

NEWS.md
service/gradle.properties
service/src/main/okapi/ModuleDescriptor-template.json

Updated NEWS.md and bumped version to 2.0.1
refs MODOA-62

chore: Release 2.0.1

---

NEWS.md

Updated NEWS.md to reflect changes in 2.0.1 release

chore: Post release 2.0.1

---

README.md

chore: Readme tweaks

---

NEWS.md
service/gradle.properties

Added NEWS section and removed SNAPSHOT from app version

chore: Post release 3.0.1

---

NEWS.md
service/gradle.properties

Removed -SNAPSHOT from appVersion and updated NEWs.md section
MODOA-68

chore: Release 3.2.0

---

NEWS.md
service/gradle.properties

Bumped version and interface version, included -SNAPSHOT and added NEWS.md section

chore: Post release 3.2.0
